<?php
// YCMusic-generate-pdf.php
require_once __DIR__ . '/admin/fpdf.php';
require_once __DIR__ . '/YCdb_connection.php';

// 1. Fetch all music events (posts with music categories)


// Only use actual categories in your DB: 'concert' and 'event'
$musicCategories = ['concert', 'event'];
$categoryLabels = [
    'concert' => 'Concert',
    'event' => 'General Event',
];

$in = str_repeat('?,', count($musicCategories) - 1) . '?';
$stmt = $pdo->prepare("SELECT * FROM posts WHERE category IN ($in)");
$stmt->execute($musicCategories);
$events = $stmt->fetchAll(PDO::FETCH_ASSOC);

// 2. Summary counts
$totalEvents = count($events);
$categoryCounts = array_fill_keys($musicCategories, 0);
$totalLikes = 0;
foreach ($events as $event) {
    $cat = $event['category'];
    if (isset($categoryCounts[$cat])) $categoryCounts[$cat]++;
    $totalLikes += (int)($event['likes'] ?? 0);
}

// 3. PDF setup
$pdf = new FPDF();
$pdf->AddPage();
$pdf->SetFont('Arial','B',16);
$pdf->Cell(0,10,'Music Events Report',0,1,'C');
$pdf->SetFont('Arial','',11);
$pdf->Cell(0,8,'Generated: ' . date('Y-m-d H:i:s'),0,1,'R');
$pdf->Ln(5);

// 4. Summary Section
$pdf->SetFont('Arial','B',13);
$pdf->Cell(0,8,'Summary',0,1);
$pdf->SetFont('Arial','',12);
$pdf->Cell(0,8,'Total Number of Music Events Uploaded: ' . $totalEvents,0,1);
$pdf->Cell(0,8,'Total Likes Received Across All Events: ' . $totalLikes,0,1);
$pdf->Ln(2);

$pdf->SetFont('Arial','B',12);
$pdf->Cell(0,8,'Category Breakdown:',0,1);
$pdf->SetFont('Arial','',12);
foreach ($categoryCounts as $cat => $count) {
    $label = $categoryLabels[$cat] ?? $cat;
    $pdf->Cell(0,8,'- ' . $label . ': ' . $count,0,1);
}
$pdf->Ln(5);

// 5. Detailed Event Records Table

$pdf->SetFont('Arial','B',13);
$pdf->Cell(0,8,'Detailed Event Records',0,1);
$pdf->SetFont('Arial','B',10);
$pdf->Cell(40,8,'Title',1);
$pdf->Cell(22,8,'Date',1);
$pdf->Cell(18,8,'Time',1);
$pdf->Cell(35,8,'Location',1);
$pdf->Cell(30,8,'Category',1);
$pdf->Cell(15,8,'Likes',1);
$pdf->Ln();
$pdf->SetFont('Arial','',9);
foreach ($events as $event) {
    $pdf->Cell(40,8,substr($event['title'],0,28),1);
    $pdf->Cell(22,8,substr($event['event_date'] ?? $event['release_date'] ?? '',0,10),1);
    $pdf->Cell(18,8,substr($event['event_time'] ?? '',0,5),1);
    $pdf->Cell(35,8,substr($event['location'] ?? '',0,22),1);
    $catLabel = $categoryLabels[$event['category']] ?? $event['category'];
    $pdf->Cell(30,8,$catLabel,1);
    $pdf->Cell(15,8,$event['likes'] ?? '0',1);
    $pdf->Ln();
}
$pdf->Ln(5);

// 6. Footer
$pdf->SetY(-30);
$pdf->SetFont('Arial','I',9);
$pdf->Cell(0,8,'Generated by Yaka Crew Band Website – Admin Panel',0,1,'C');
$pdf->Cell(0,8,'Copyright © ' . date('Y') . ' Yaka Crew Band. All rights reserved.',0,1,'C');
// Page numbering
$pdf->AliasNbPages();
$pdf->SetY(-15);
$pdf->SetFont('Arial','I',8);
$pdf->Cell(0,10,'Page '.$pdf->PageNo().' of {nb}',0,0,'C');

$pdf->Output('D', 'YakaCrew_Music_Events_Report.pdf');
exit;
