<?php
// YCVideo-generate-pdf.php
require_once __DIR__ . '/admin/fpdf.php';
require_once __DIR__ . '/YCdb_connection.php';

// 1. Fetch all audio & video uploads from 'songs' and 'video' tables
$songs = $pdo->query("SELECT * FROM songs")->fetchAll(PDO::FETCH_ASSOC);
$videos = $pdo->query("SELECT * FROM video")->fetchAll(PDO::FETCH_ASSOC);

$allUploads = [];
foreach ($songs as $s) {
    $allUploads[] = array_merge($s, [
        'upload_type' => 'Audio',
        'media_file' => $s['media_file'] ?? '',
        'cover_image' => $s['cover_image'] ?? ($s['image_path'] ?? ($s['thumbnail_path'] ?? '')),
        'location' => $s['category'] ?? '',
        'music_category' => $s['music_category'] ?? '',
        'artist' => $s['artist_name'] ?? '',
        'hit_count' => $s['hits'] ?? '',
        'upload_datetime' => $s['created_at'] ?? '',
        'description' => $s['description'] ?? '',
    ]);
}
foreach ($videos as $v) {
    $allUploads[] = array_merge($v, [
        'upload_type' => 'Video',
        'media_file' => $v['media_file'] ?? '',
        'cover_image' => $v['cover_image'] ?? ($v['image_path'] ?? ($v['thumbnail_path'] ?? '')),
        'location' => $v['category'] ?? '',
        'music_category' => $v['music_category'] ?? '',
        'artist' => $v['artist_name'] ?? '',
        'hit_count' => $v['hits'] ?? '',
        'upload_datetime' => $v['created_at'] ?? '',
        'description' => $v['description'] ?? '',
    ]);
}

// 2. Summary counts
$totalUploads = count($allUploads);
$typeCounts = ['Audio' => 0, 'Video' => 0];
$locationCounts = ['latest' => 0, 'top' => 0, 'video' => 0];
$categoryCounts = [];
foreach ($allUploads as $u) {
    $typeCounts[$u['upload_type']]++;
    $loc = strtolower($u['location']);
    if (isset($locationCounts[$loc])) $locationCounts[$loc]++;
    $cat = $u['music_category'] ?? '';
    if ($cat) $categoryCounts[$cat] = ($categoryCounts[$cat] ?? 0) + 1;
}

// 3. PDF setup
$pdf = new FPDF();
$pdf->AddPage();
$pdf->SetFont('Arial','B',16);
$pdf->Cell(0,10,'Audio & Video Uploads Report',0,1,'C');
$pdf->SetFont('Arial','',11);
$pdf->Cell(0,8,'Generated: ' . date('Y-m-d H:i:s'),0,1,'R');
$pdf->Ln(5);

// 4. Summary Section
$pdf->SetFont('Arial','B',13);
$pdf->Cell(0,8,'Summary',0,1);
$pdf->SetFont('Arial','',12);
$pdf->Cell(0,8,'Total Uploads: ' . $totalUploads,0,1);
$pdf->Cell(0,8,'Uploads by Type: Audio (' . $typeCounts['Audio'] . '), Video (' . $typeCounts['Video'] . ')',0,1);
$pdf->Cell(0,8,'Uploads by Location: Latest Songs (' . $locationCounts['latest'] . '), Top Albums (' . $locationCounts['top'] . '), Video (' . $locationCounts['video'] . ')',0,1);
$pdf->Cell(0,8,'Uploads by Music Category:',0,1);
foreach ($categoryCounts as $cat => $count) {
    $pdf->Cell(0,8,'- ' . ucfirst(str_replace('_',' ',$cat)) . ': ' . $count,0,1);
}
$pdf->Ln(5);

// 5. Detailed Upload Records Table
$pdf->SetFont('Arial','B',13);
$pdf->Cell(0,8,'Detailed Upload Records',0,1);
$pdf->SetFont('Arial','B',8);
$pdf->Cell(28,8,'Title',1);
$pdf->Cell(30,8,'Description',1);
$pdf->Cell(18,8,'Artist',1);
$pdf->Cell(14,8,'Type',1);
$pdf->Cell(16,8,'Location',1);
$pdf->Cell(20,8,'Category',1);
$pdf->Cell(22,8,'Upload Date',1);
$pdf->Cell(14,8,'Hit Cnt',1);
$pdf->Ln();
$pdf->SetFont('Arial','',7);
foreach ($allUploads as $u) {
    $pdf->Cell(28,8,substr($u['title'] ?? '',0,18),1);
    $pdf->Cell(30,8,substr($u['description'] ?? '',0,20),1);
    $pdf->Cell(18,8,substr($u['artist'] ?? '',0,12),1);
    $pdf->Cell(14,8,$u['upload_type'],1);
    $pdf->Cell(16,8,ucfirst($u['location']),1);
    $pdf->Cell(20,8,ucfirst(str_replace('_',' ',$u['music_category'])),1);
    $pdf->Cell(22,8,substr($u['upload_datetime'],0,16),1);
    $pdf->Cell(14,8,($u['location'] === 'top' ? $u['hit_count'] : ''),1);
    $pdf->Ln();
}
$pdf->Ln(5);

// 6. Footer
$pdf->SetY(-30);
$pdf->SetFont('Arial','I',9);
$pdf->Cell(0,8,'Generated by Yaka Crew Band Website – Admin Panel',0,1,'C');
$pdf->Cell(0,8,'Copyright © ' . date('Y') . ' Yaka Crew Band. All rights reserved.',0,1,'C');
// Page numbering
$pdf->AliasNbPages();
$pdf->SetY(-15);
$pdf->SetFont('Arial','I',8);
$pdf->Cell(0,10,'Page '.$pdf->PageNo().' of {nb}',0,0,'C');

$pdf->Output('D', 'YakaCrew_Audio_Video_Report.pdf');
exit;
